# Node '1'

[metadata]
title = "Inception"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0852.html"}
a = "Proposal"

[doc.html.body.main]
blocks = [
"""
Railway stations age like old words. With every repetition we precipitate new meaning.
""",
"""
<Broadstairs>   So there ought to be another train in... Wait a moment.
<Chalgrove>     I've lost sight of him again.
<Appleby>       Here I am.
<Broadstairs>   In an hour or so. Eighty minutes.
""",
"""
We're in a country town very welcoming to visitors.
Too many of its fine men fled to Hughenden, so in 1848 they made this terminus in a Tudor style.
For sure, it facilitates departures, but secretly it invites us to stay.
""",
"""
<Broadstairs>   Anyone hungry?
<Appleby>       I'd like to [wander around](0852.html) first.
<Chalgrove>     Let's not forget, we need to keep an eye on the time.
""",
]
