# Node '1'

[metadata]
title = "Inception"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0852.html"}
a = "Proposal"

[doc.html.body.main]
blocks = [
"""
Railway stations are like old words. We use them differently these days.
""",
"""
<Broadstairs>   So there ought to be another train in... Wait a minute.
<Chalgrove>     I've lost sight of him again.
<Appleby>       Here I am.
<Broadstairs>   In an hour or so. Eighty minutes.
""",
"""
We're in a country town. You probably know it.
Too many of its great men fled to Hughenden, so in 1848 they made this terminus in a Tudor style.
For sure, it facilitates departures, but secretly it invites us to stay.
""",
"""
<Broadstairs>   We don't have to go just yet, chaps. There'll be another train in an hour or so.
<Chalgrove>     I've lost sight of him again.
<Appleby>       Here I am.
""",
]
