# Node '2'

[metadata]
title = "Elaboration"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1136.html"}
a = "Promise"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1266.html"}
a = "Offer"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4578.html"}
a = "Disinclination"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4646.html"}
a = "Withdrawal"

[doc.html.body.main]
blocks = """
Broadstairs leads the way. He is upright and smart on every bearing.
He is gaff-rigged with an iron keel.

To consult with Broadstairs is to discover a beneficent uncle.
To engage him awakens a mighty foe.
His letterhead crowns only solemn undertakings.
His monogram makes most weighty the deed.

He is sincere in every syllable. So he will spare you the details.
You will be unable to recall exactly what was promised.
And when he gives his Word, his Word comes not with a word.
The Word of Broadstairs is a nod. An affirming smile. An intoxicating handshake.

And now, as he strides up St Mary's towards the Dogpole, he radiates aureolar illocutionary assurance.

Appleby regards the [shopfront suspiciously](1266.html).
Chalgrove is unhappy too, but why?
He's looking at his watch. If they follow [the river](4578.html), they can loop back in time for the train.

Broadstairs needs convincing. He has half a mind to [call it a day](4646.html).
Otherwise, what's wrong with a [pub](1136.html)?
"""
