# Node '2'

[metadata]
title = "Elaboration"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1136.html"}
a = "Promise"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1266.html"}
a = "Offer"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4578.html"}
a = "Disinclination"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4646.html"}
a = "Withdrawal"

[doc.html.body.main]
blocks = """
Appleby regards the [shopfront suspiciously](1266.html).
Chalgrove is unhappy too, but why?
He's looking at his watch. If they follow [the river](4578.html), they can loop back in time for the train.

Broadstairs needs convincing. He has half a mind to [call it a day](4646.html).
Otherwise, what's wrong with a [pub](1136.html)?
"""
