# Node '3'

[metadata]
title = "Construction"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1176.html"}
a = "Delivery"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4984.html"}
a = "Disavowal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5082.html"}
a = "Cancellation"

[doc.html.body.main]
blocks = [
"""
So they decide on the Admiral Benbow. A cosy little place with plenty of character.
Chalgrove does a quick check for anything untoward.
Any hint of trouble and he would be [straight out the door](4984.html).
But at first glance all the signs are familiar. All the words are well-known.
""",
"""
<Broadstairs>   They have a beer called Rail Replacement Service. It's an IPA.
<Appleby>       No, a pint of Stout I think.
<Chalgrove>     Gin and Tonic please.
""",
"""
They have chosen a spot in the yard at the back. It has a little roof to keep off the weather.
The seats are nice and dry. It's plenty warm enough.
Just as he's about to relax, Chalgrove's eyes settle on something he doesn't understand.
""",
"""
<Chalgrove>     Would you check that beer mat for me? The logo. Do you recognize it?
<Appleby>       deBilito. No. It doesn't seem to connect to anything.
<Chalgrove>     How did it get there? Did it follow us in?
""",
"""
Broadstairs comes back with [drinks and menus](1176.html). The writing has not escaped him either.
They all sit down to puzzle over the bit of new vocabulary.
<Appleby>       Whatever can exist, does exist.
<Chalgrove>     Then why haven't we seen it before? I think we should [leave](5082.html).
""",
]
