# Node '3'

[metadata]
title = "Construction"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1176.html"}
a = "Delivery"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4984.html"}
a = "Disavowal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5082.html"}
a = "Cancellation"

[doc.html.body.main]
blocks = [
"""
Settling in nicely at the Admiral Benbow.
All the signs are familiar. All the words well-known
""",
"""
<Broadstairs>   They have a beer called Rail Replacement Service. It's an IPA.
<Appleby>       Oh. No, a pint of Stout I think.
<Chalgrove>     Gin and Tonic please.
""",
"""
They have chosen a spot in the yard at the back.
Chalgrove's eyes settle on something he doesn't understand.
""",
"""
<Chalgrove>     That was very strange in the street back there.
<Appleby>       Yes it affected me too.
<Chalgrove>     Can you check that beer mat for me?
<Appleby>       deBilito.
<Chalgrove>     I think I might just [get out of here](4984.html).
<Appleby>       We should [leave together](5082.html) then.
""",
"""
Broadstairs comes back with [drinks and menus](1176.html).
""",
]
