# Node '4'

[metadata]
title = "Evaluation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1218.html"}
a = "Adoption"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5194.html"}
a = "Refusal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5304.html"}
a = "Cancellation"

[doc.html.body.main]
blocks = """
<Broadstairs>   Do we have a stable representation of our situation? [An interpretation](1218.html)?
<Chalgrove>     OK, here's what we know. A new word has appeared. And it is propagating everywhere.
<Appleby>       No, we are witnessing a process. Language is action.
<Chalgrove>     Action by whom?
<Appleby>       I don't know. But forget where you think you are.
                If I'm right we're part of some sort of poietic process.
<Broadstairs>   [More observations](5194.html) required then.
"""
