# Node '4'

[metadata]
title = "Evaluation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1218.html"}
a = "Adoption"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5194.html"}
a = "Refusal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5304.html"}
a = "Cancellation"

[doc.html.body.main]
blocks = """
It actually rather fun.
<Chalgrove>     So here's what we know. A new word has appeared. And it is propagating everywhere.
<Broadstairs>   The propagation is a Heideggerian breakdown. deBilito was here before we arrived.
<Appleby>       No, we are witnessing a process. Language is action.
<Appleby>       We [get slaughtered](5194.html) and you do nothing about it.
<Chalgrove>     de Bilito can borrow on a very easy schedule.
<Broadstairs>   Do we have a stable representation of our situation? [different strategy](1218.html).
<Appleby>       Every representation is an interpretation.
"""
