# Node '4'

[metadata]
title = "Evaluation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1218.html"}
a = "Adoption"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5194.html"}
a = "Refusal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5304.html"}
a = "Cancellation"

[doc.html.body.main]
blocks = """
It actually rather fun.
<Chalgrove>     So here's what we know. A new word has appeared. And it is propagating everywhere.
<Broadstairs>   I think that 'propagation' as you say is really Heideggerian breakdown.
                deBilito was here before we arrived. It's a historical token. It's dead.
                We're seeing it now because there's been a shift in the domain.
<Appleby>       No, we are witnessing a process. Language is action.
<Chalgrove>     Action by whom?
<Appleby>       I don't know. But forget where you think you are.
                This a topological system. We're part of some sort of poietic process.
<Appleby>       We [get slaughtered](5194.html) and you do nothing about it.
<Chalgrove>     de Bilito can borrow on a very easy schedule.
<Broadstairs>   Do we have a stable representation of our situation? [different strategy](1218.html).
<Appleby>       Every representation is an interpretation.
"""
