# Node '5'

[metadata]
title = "Completion"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "6401.html"}
a = "Revisit"

[doc.html.body.main]
blocks = """
Appleby is quiet for a moment. He looks happier now.

<Chalgrove>     OK, is it time for another round?
<Broadstairs>   Let's [keep moving](6401.html). I'd like to try further down the street.
<Appleby>       All we need to do now is figure out the nature of
                [this loop](https://tundish.github.io/junkdlc/1-dialogue-and-action.html)
                we seem to be in.
"""
