# Node '6'

[metadata]
title = "Discussion"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4510.html"}
a = "Clarification"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4720.html"}
a = "Disinclination"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4806.html"}
a = "Withdrawal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "4892.html"}
a = "Confirmation"

[doc.html.body.main]
blocks = [
"""
<Appleby>       I thought I heard shouting.
                Someone said, "They've closed the bridges". I asked which bridges, and they said, "all of them".
<Chalgrove>     What, just now?
<Appleby>       So I ran down to English Bridge and it was blocked. They'd put a cordon across it.
<Chalgrove>     But the traffic is flowing. I can see cars crossing the river.
""",
"""
Chalgrove rarely takes a stand but he won't tolerate an inaccuracy.
""",
"""
<Appleby>       See that, I'm still sweating from coming back up the hill.
                They had these red barriers, and signs. With a name on them. I'm trying to think.
                Began with a 'D'.
<Broadstairs>   deBilito. There.
""",
"""
The bins in the alley across from them were stamped with that very name.

They looked about them.

Ten red flags which hung from the Market House were embroidered with the identical word.
Like battle standards in some unifactional war, where each family claims the same crest.

Wherever they turned they saw it on billboards and shop signs.
Even the Cenotaph bore the brand of deBilito.
""",
"""
<Chalgrove>     That's extraordinary. I'm sure I didn't see that before.
<Broadstairs>   Appleby, [where are you going](4892.html)?
                I want everyone to [stay together](4510.html).
""",
]
