# Node '9'

[metadata]
title = "Cancelled"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "6265.html"}
a = "Revisit"

[doc.html.body.main]
blocks = [
"""
<Broadstairs>   Orderly retreat. I agree, that's the right call.
<Chalgrove>     We aren't in a position to make a serious analysis with the evidence we have.
<Appleby>       I think with more preparation we could have done a better job.
""",
"""
Broadstairs sinks his pint in exactly the time it takes Chalgrove to retie a shoelace.
The three move [outside](6265.html).
""",
]
