# Node '9'

[metadata]
title = "Cancelled"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "6265.html"}
a = "Revisit"

[doc.html.body.main]
blocks = [
"""
<Broadstairs>   Orderly retreat. I agree, that's the right call.
<Appleby>       We aren't in a position to make a comprehensive analysis. Not with the evidence we have.
<Chalgrove>     I think with more observation we could have done a better job. But we've run out of time.
""",
"""
Broadstairs sinks his pint in exactly the time it takes Chalgrove to retie a shoelace.
The three move [outside](6265.html).
""",
]
