# Edge 'a'

[metadata]
title = "Proposal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0836.html"}
a = "Elaboration"

[doc.html.body.main]
blocks = [
"""
About Chalgrove.
Content to believe that things happen elsewhere.
Meticulous. Conscientious. Dutiful.
Broadstairs is not comfortable with the idea of a *wander*. He needs an objective.
He has never understood Appleby's methods.

Chalgrove clears his throat.
""",
"""
<Chalgrove>     Look, if we can just go [up the hill](0836.html) a bit,
                we can get away from the traffic and work out where we want to go.
""",
"""
It's a trusted old formula, and it works.
""",
]
