# Edge 'a'

[metadata]
title = "Proposal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0836.html"}
a = "Elaboration"

[doc.html.body.main]
blocks = [
"""
Many people, wishing to point at the epitome of mindless bureacracy,
have indicated to me the character of Chalgrove.

Unfair, say I. Granted, he is meticulous, conscientious and dutiful.
Mindless, however, he is not.

His mind exists, even downright persists, by virtue of his daily routine.
It is laid out in a grid pattern, and castellated in certain critical ratios.
A measure of seven splits into a two and a five.
Where precision is required (and Chalgrove does enjoy precision)
twenty-four is employed as the divisor.

This cerebral containment resembles, perhaps, the rear garden of a modern family home.
Never quite embracing nature; the planters positioned according to policy,
and the greenery only from certain Approved Suppliers.

Content to believe that things happen elsewhere.
Broadstairs is not comfortable with the idea of a *wander*. He needs an objective.
He has never understood Appleby's methods.

Chalgrove clears his throat.
""",
"""
<Chalgrove>     Look, if we can just go [up the hill](0836.html) a bit,
                we can get away from the traffic and work out where we want to go.
""",
"""
It's a trusted old formula, and it works.
""",
]
