# Edge 'b'

[metadata]
title = "Promise"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0838.html"}
a = "Construction"

[doc.html.body.main]
blocks = [
"""
Verse?
Appleby, the bloodhound, is already ahead. He has found.
Broadstairs the oaken General.
Chalgrove monitors all.
""",
"""
<Broadstairs>   Pie and chips? Or Welsh Rarebit?
                Some place where we can smoke and sit.
                I raise my glass
                And hope that we don't miss our train.

<Appleby>       I would much rather look around.

<Chalgrove>     Alas, forever torn in twain!
                This Bloodhound and this Oaken Thegn
                Are going to make me miss my train
                And argue with the wife again.
""",
]
