# Edge 'c'

[metadata]
title = "Delivery"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0840.html"}
a = "Evaluation"

[doc.html.body.main]
blocks = [
"""
<Broadstairs>   I hope you haven't lost your appetite.
<Appleby>       What's it say on the back of that menu?
<Broadstairs>   Reciprocus. They do a Beef Wellington.
""",
"""
Broadstairs is invulnerable when he has a glass in his hand.
Chalgrove, on the other hand, has developed an aversion to his Gin and Tonic.
Appleby takes a tug on his pint. It is a Brown Ale.
""",
"""
<Broadstairs>   What do we think about this new arrival then?
<Chalgrove>     It's popping up everywhere.
<Appleby>       That's just Heideggerian breakdown.
                Reciprocus was probably here all along.
                You're seeing it now because of a shift in the linguistic domain.
""",
]
