# Edge 'g'

[metadata]
title = "Offer"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0844.html"}
a = "Discussion"

[doc.html.body.main]
blocks = [
"""
Let me remind you about Appleby. Because he's hard to pin down.

Appleby has no history. His consciousness is a parade of morphing images and transient sensations.
It is by this he perceives many secret worlds. One of these is our own.
He comprehends it only by the study of these internal projections.

Appleby is locked in a continual struggle of, on dreaming himself somewhere,
having all the while to reconcile with the contradictary sensations of his physical contemporanity.

So you may find him absent. But he is always there. Noticing and questioning, never still.
A rare breed of investigator, uncommitted to everything but the discovery.
""",
"""
<Broadstairs>   I'd like to make some progress before Appleby wanders off again.
""",
"""
Appleby doesn't care who's in charge. His impulses originate in a different realm.
He doesn't resent authority. He has learned that there is no such thing.
""",
"""
<Broadstairs>   We're a man down already. That didn't take long. Where is he now?
<Chalgrove>     He's [over there](0844.html).
""",
]
