# Edge 'g'

[metadata]
title = "Offer"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0844.html"}
a = "Discussion"

[doc.html.body.main]
blocks = [
"""
Let me remind you about Appleby. Because he's hard to pin down.

Appleby has no history. His consciousness is a parade of morphing images and transient sensations.
He sees only by the light of this internal projection.
It is the means by which he communicates with many secret worlds.

Appleby is locked in a continual struggle of, on dreaming himself somewhere,
having all the while to reconcile with the contradictary sensations of his physical contemporanity.

So you may find him absent. But he is always there. Noticing and questioning, never still.
A rare breed of investigator, uncommitted to everything but the discovery.
""",
"""
<Broadstairs>   Not sure how we're to choose a pub. There must be one on every corner.
<Chalgrove>     I do fancy a pint.
""",
"""
Appleby doesn't care to be in charge. He understands there's no such thing.
""",
"""
<Broadstairs>   We're a man down.
<Chalgrove>     He's [over there](0844.html).
""",
]
