# Edge 'g'

[metadata]
title = "Offer"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0844.html"}
a = "Discussion"

[doc.html.body.main]
blocks = [
"""
About Appleby.
Street scene.
""",
"""
<Broadstairs>   Not sure how we're to choose a pub. There must be one on every corner.
<Chalgrove>     I do fancy a pint.
""",
"""
Mystery prose.
""",
"""
<Broadstairs>   We're a man down.
<Chalgrove>     He's [over there](0844.html).
""",
]
