# Edge 'g'

[metadata]
title = "Offer"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0844.html"}
a = "Discussion"

[doc.html.body.main]
blocks = [
"""
About Appleby.
Appleby has no history. His consciousness is a parade of morphing images and transient sensations.
He lives by the light of this internal projection.
It is the means by which he communicates with many worlds.
Appleby is a character not without contradictions.
He is in a continual struggle of dreaming himself somewhere
and having all the while to reconcile with the contemporaneous sensations of his physical disposition.

So you may find him twitchy.

Interpenetrating.
Watchful, discriminating.
Uncommitted investigator.
Hunts Phantasms.
Street scene.
""",
"""
<Broadstairs>   Not sure how we're to choose a pub. There must be one on every corner.
<Chalgrove>     I do fancy a pint.
""",
"""
Appleby doesn't care to be in charge. He understands there's no such thing.
""",
"""
<Broadstairs>   We're a man down.
<Chalgrove>     He's [over there](0844.html).
""",
]
