# Edge 'e'

[metadata]
title = "Disinclination"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0848.html"}
a = "Withdrawn"

[doc.html.body.main]
blocks = [
"""
They follow a brick-lined lane and pass under the battlements to the water.
""",
"""
<Chalgrove>     We won't get lost if we keep to the river.
""",
"""
Appleby looks bored. Broadstairs is [not impressed](0848.html) either.
""",
]
