# Edge 'e'

[metadata]
title = "Disinclination"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0848.html"}
a = "Withdrawn"

[doc.html.body.main]
blocks = [
"""
Chalgrove favours a narrow brick-lined lane which passes under the old wall.
""",
"""
<Broadstairs>   Water Lane. Are you sure you want to go this way?
<Chalgrove>     We won't get lost if we keep to the river.
""",
"""
Appleby looks bored. Broadstairs is not very impressed either.
""",
"""
<Chalgrove>     This arch is Thirteenth Century, I believe.
""",
"""
Or perhaps older than that. It's called [Traitor's Gate](0848.html).
That's the way they go now.
""",
]
