# Edge 'j'

[metadata]
title = "Withdrawal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0848.html"}
a = "Withdrawn"

[doc.html.body.main]
blocks = [
"""
<Broadstairs>   Whatever's happened here, I don't want us to go in unprepared.
<Chalgrove>     Agreed.
<Appleby>       You want to [go back](0848.html) then?
<Chalgrove>     I think so.
<Broadstairs>   Under the circumstances.
""",
]
