# Edge 'j'

[metadata]
title = "Withdrawal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0848.html"}
a = "Withdrawn"

[doc.html.body.main]
blocks = [
"""
<Chalgrove>     Look chaps. I really don't want to be late back again.
<Broadstairs>   You want to [head off home](0848.html) then?
<Chalgrove>     I think so.
<Appleby>       We've got a bit of time though, surely.
""",
]
