# Edge 'k'

[metadata]
title = "Confirmation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0838.html"}
a = "Construction"

[doc.html.body.main]
blocks = [
"""
<Broadstairs>   Where's he going?
<Chalgrove>     He's gone into that terrace on the right there.
<Appleby>       Every single one. They've bought up the whole row.
""",
"""
Crimson minims on identical white staves.
Chained the undulating doorways in regular, measured intervals.
""",
]
