# Edge 'k'

[metadata]
title = "Confirmation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0838.html"}
a = "Construction"

[doc.html.body.main]
blocks = [
"""
Chalgrove is rattled now. His itinerary is ruined, and in place
of his regular schedule turns the first reel of a surrealistic nightmare.
Thank goodness for Broadstairs, who remains unbuffeted. Grave admittedly, but calm.
""",
"""
<Broadstairs>   Let him go forward. There'll be game.
<Chalgrove>     We can't leave him to run off all the time like that. He needs to come to heel.
<Broadstairs>   Not yet. When he points up, then it's flush and fire.
""",
"""
Appleby courses left, trailing his fingers against the stone and brick.
Then suddenly right, into a pretty cobbled street. Old barns walled up into cottages.
No yards before the short painted doors, just a neat running gutter.

He cocks his head up to listen.
A glissando of crimson minims on identical white staves chain the undulating frontages
in linking measured intervals.
Each one declared under management of Reciprocus.
""",
"""
<Broadstairs>   All right, I've seen enough. We need to [lay up somewhere](0838.html)
and figure out what's going on.
""",
]
