# Edge 'm'

[metadata]
title = "Cancellation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0850.html"}
a = "Cancelled"

[doc.html.body.main]
blocks = [
"""
Broadstairs is about to peruse the menu. Best to interrupt him now before he gets used to the idea of eating.
""",
"""
<Appleby>       We're thinking of [getting back](0850.html). As in, immediately.
<Chalgrove>     Yes, whatever's going on here, we can't have any part of it.
<Broadstairs>   Hmmm.
""",
"""
Broadstairs knows that his capacity to lead correlates very strongly with the willingness of
the men to be led.
""",
]
