# Edge 'l'

[metadata]
title = "Refusal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0838.html"}
a = "Construction"

[doc.html.body.main]
blocks = [
"""
It's been a while since anybody spoke. Appleby leans forward to relight his cigar.
He is intrigued to discover that it is still in its wrapper.
""",
"""
<Appleby>       It's only a guess, but I believe we've found our way into
                some sort of recurrent structure.
<Chalgrove>     A Florean Winograde?
<Appleby>       Feels like it. But it's self-cyclic.
""",
"""
Broadstairs steps in. It's time to draw up a plan. Give people some jobs to do.
""",
"""
<Broadstairs>   First priority then is to establish the scale of the temporal domain.
<Chalgrove>     We should log any occurrences of semiotic failure.
                Some residue that might point us toward the origin.
<Broadstairs>   If we get separated, let's try to meet up again here.
<Appleby>       Agreed. But be prepared for repetition.
""",
"""
Broadstairs is delighted. It seems they've agreed to [stay in the pub](0838.html).
""",
]
