# Edge 'n'

[metadata]
title = "Cancellation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0850.html"}
a = "Cancelled"

[doc.html.body.main]
blocks = """
They mistake for a Material token.

<Broadstairs>   It's a common mistake to think of the enemy as a single entity.
                The larger the organization, the more it is riven with rivalry.
<Chalgrove>     A big firm can often be a cluster of fiefdoms.
<Broadstairs>   The only thing they share is the name.
<Chalgrove>     Underneath it's all chaos. I've seen it myself.
<Appleby>       What are you suggesting?
"""
