# Node '4'

[metadata]
title = "Evaluation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1218.html"}
a = "Adoption"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5194.html"}
a = "Refusal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5304.html"}
a = "Cancellation"

[doc.html.body.main]
blocks = """
This is the crisis point.
<Appleby>       Something something.
<Bullingdon>    And what do you mean by that?
<Chalgrove>     That's rather uncalled for, Appleby.
<Appleby>       We got slaughtered and you did nothing about it.
<Chalgrove>     de Bilito can borrow on very easy terms, I hear.
<Bullingdon>    We can't beat them toe to toe. We need a different strategy.
"""
