# Node '4'

[metadata]
title = "Evaluation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "1218.html"}
a = "Adoption"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5194.html"}
a = "Refusal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "5304.html"}
a = "Cancellation"

[doc.html.body.main]
blocks = """
evaluation
"""
